# Generated by Django 5.1.1 on 2025-02-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.TextField()),
                ('fax_number', models.CharField(max_length=20)),
                ('telephone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_person_telephone_number', models.CharField(max_length=20)),
                ('managing_director', models.CharField(max_length=255)),
                ('managing_director_telephone_number', models.CharField(max_length=20)),
                ('managing_director_email', models.EmailField(max_length=254)),
                ('products', models.TextField()),
                ('services', models.TextField()),
            ],
        ),
    ]
